algoritmo "semnome"
// Função :
// Autor :
// Data : 18/06/2019
// Seção de Declarações 
var
valor1, valor2: inteiro
inicio
Escreval ("Digite o valor inicial da contagem:")
leia (valor1)
Escreval ("Digite o valor final da contagem:")
leia (valor2)
Se (valor1<valor2)entao
   enquanto (valor1<=valor2) faca
   escreval (valor1)
   valor1<- valor1 +1
   fimenquanto
Senao
   enquanto (valor1 >=valor2) faca
   escreval (valor1)
   valor <- (valor1-1)
   fimenquanto
fimse
fimalgoritmo
