algoritmo "matriz20x20"
// Função :
// Autor : Isabelle Damacena
// Data : 24/09/2019
// Seção de Declarações 
var
num: vetor [1..20,1..20] de inteiro
x, y, result: inteiro
inicio
 para x de 1 ate 20 faca
       para y de 1 ate 20 faca
          escreval ("Preencha os valores:")
          leia (num [x,y])
          escreval (num[x,y]:3)
          
          
//Exercício não terminado.


fimalgoritmo
