algoritmo "parametroreferencia"
// Função :
// Autor :
// Data : 30/09/2019
// Seção de Declarações 
var
x, y: Inteiro
procedimento Soma (var A, B: Inteiro)
inicio
      A<- A + 1
      B<- B + 2
      escreval ("Valor de A =", A)
      escreval ("Valor de B =", B)
      escreval ("Soma A + B =", A+B)
fimprocedimento
inicio
      x<- 4
      y<- 8
      Soma (x, y)
      escreval ("Valor de X= ", x)
      escreval ("Valor de y = ", Y)
fimalgoritmo
