algoritmo "somafuncao"
// Função :
// Autor :
// Data : 30/09/2019
// Seção de Declarações 
var
 V1, V2, S: inteiro
 funcao soma (x, y: Inteiro): Inteiro
 inicio
       retorne x + y
 fimfuncao
inicio
      escreva ("Digite o primeiro valor: ")
      leia (V1)
      escreva ("Digite o segundo valor: ")
      leia (V2)
      S<- Soma (V1, V2)
      escreva ("A soma entre ", V1, " e ", V2, " é igual à " ,S)
fimalgoritmo
